### ISSUE TITLE
When scheduling bills, a future transaction should have a scheduled indicator

### ISSUE THREAD

**Issue by jonathan-irvin** [two-jelly-beans/jelly-fin#31]
**Is your feature request related to a problem? Please describe.**
Planning is crucial.  Typically bills are paid in advance if done right.  If you have several bills, it can be a hassle determining which ones you've scheduled. 

**Describe the solution you'd like**
There should be a way to determine if a bill has been scheduled or not.  Maybe this is a checkbox.

**Comment by misterhtmlcss** [comment]
I actually think it's not clear what you are referring to here. Do you have a screenshot? Is there some where I should be looking to understand this question further?

**Comment by RozzaysRed** [comment]
I could be wrong but the way I interpreted it was like you have a bill that's due the 25th of every month but you have it scheduled to go out on the 16th of every month, this would track which bills are already scheduled and which aren't so that you know which are going to go out of your account automatically and which you have to actually pay.

If this is the case, I would suggest including the date at which the bill is being paid.  I know I always forget which days my bills go out on since they are different days so if we go with idea of scheduled bills and not, I think a date should be included so that the user could essentially plan ahead.

Thoughts?

**Comment by jonathan-irvin** [comment]
> I could be wrong but the way I interpreted it was like you have a bill that's due the 25th of every month but you have it scheduled to go out on the 16th of every month, this would track which bills are already scheduled and which aren't so that you know which are going to go out of your account automatically and which you have to actually pay.

So, the main example is we typically know the bills a month in advance, so shortly before the beginning of the month, my wife will go and either schedule the bills online (like a credit card payment) or doing bill pay through our bank.  So, in reality, it could be as simple as a checkbox just to verify which bills have been scheduled and which have yet to be scheduled. Some bills you don't know the amount until later in the month, but you still know they will need to be eventually paid.
 
> If this is the case, I would suggest including the date at which the bill is being paid. I know I always forget which days my bills go out on since they are different days so if we go with idea of scheduled bills and not, I think a date should be included so that the user could essentially plan ahead.

Maybe we can do this two ways.  You input a date in which the bill will be paid and on the UI, it will be represented as a checkmark.

**Comment by jonathan-irvin** [comment]
This issue was moved to jelly-fin/jelly-fin-web#9
